config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :picks
  resources :teams
  resources :leagues
  resources :drafts
  root to: 'drafts#index'
  get 'players/search'

  resources :picks do
    get :autocomplete_player_name, on: :collection
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/pick.rb
# frozen_string_literal: true

class Pick < ApplicationRecord
  belongs_to :player
  validates_presence_of :player, presence: true

  belongs_to :draft
  validates_presence_of :draft, presence: true

  after_create_commit { broadcast_prepend_to 'picks' }
  after_update_commit { broadcast_replace_to 'picks' }
  after_destroy_commit { broadcast_remove_to 'picks' }
end

app/controllers/picks_controller.rb
# frozen_string_literal: true

class PicksController < ApplicationController
  before_action :set_pick, only: %i[show edit update destroy]
  autocomplete :player, :name

  # GET /picks
  # GET /picks.json
  def index
    @picks = Pick.all
  end

  # GET /picks/1
  # GET /picks/1.json
  def show
    @pick = Pick.new
  end

  # GET /picks/new
  def new
    @pick = Pick.new
  end

  # GET /picks/1/edit
  def edit; end

  # POST /picks
  # POST /picks.json
  def create
    @pick = Pick.new(pick_params)

    respond_to do |format|
      if @pick.save
        format.html { redirect_to draft_path(@pick.draft_id), notice: 'Pick was successfully created.' }
        format.json { render :show, status: :created, location: @pick }
      else
        format.html { render :new }
        format.json { render json: @pick.errors, status: :unprocessable_entity }
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@pick, partial: 'picks/form', locals: { pick: @pick }) }
      end
    end
  end

  # PATCH/PUT /picks/1
  # PATCH/PUT /picks/1.json
  def update
    respond_to do |format|
      if @pick.update(pick_params)
        format.html { redirect_to @pick, notice: 'Pick was successfully updated.' }
        format.json { render :show, status: :ok, location: @pick }
      else
        format.html { render :edit }
        format.json { render json: @pick.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /picks/1
  # DELETE /picks/1.json
  def destroy
    @pick.destroy
    respond_to do |format|
      format.html { redirect_to picks_url, notice: 'Pick was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_pick
    @pick = Pick.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def pick_params
    params.require(:pick).permit(:player_id, :draft_id)
  end
end

app/helpers/picks_helper.rb
module PicksHelper
end

app/views/picks/_form.html.erb
<%= form_with(model: pick, id: dom_id(pick)) do |form| %>
  <% if pick.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pick.errors.count, "error") %> prohibited this pick from being saved:</h2>

      <ul>
        <% pick.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <input type="search" id="player_chooser" name="player_chooser" placeholder="Enter name..." data-behavior="autocomplete" >

  <%= form.hidden_field :draft_id, value: @draft.id %>
  <%= form.hidden_field :player_id, value: nil %>

  <div class="actions">
    <%= form.submit "Submit Pick" %>
  </div>
<% end %>

app/views/picks/_pick.html.erb
<%= turbo_frame_tag dom_id(pick) do %>
  <div class="pick">
    <%= pick.player.name %>
      <div class="btn-group float-right">
        <%= button_to 'Delete', pick, method: :delete, class: "btn btn-danger" %>
      </div>
  </div>
<% end %>

app/views/picks/edit.html.erb
<h1>Editing Pick</h1>

<%= render 'form', pick: @pick %>

<%= link_to 'Show', @pick %> |
<%= link_to 'Back', picks_path %>

app/views/picks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Picks</h1>

<table>
  <thead>
    <tr>
      <th>Player</th>
      <th>Draft</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @picks.each do |pick| %>
      <tr>
        <td><%= pick.player_id %></td>
        <td><%= pick.draft_id %></td>
        <td><%= link_to 'Show', pick %></td>
        <td><%= link_to 'Edit', edit_pick_path(pick) %></td>
        <td><%= link_to 'Destroy', pick, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pick', new_pick_path %>

app/views/picks/new.html.erb
<h1>New Pick</h1>

<%= render 'form', pick: @pick %>

<%= link_to 'Back', picks_path %>

app/views/picks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Player:</strong>
  <%= @pick.player_id %>
</p>

<p>
  <strong>Draft:</strong>
  <%= @pick.draft_id %>
</p>

<%= link_to 'Edit', edit_pick_path(@pick) %> |
<%= link_to 'Back', picks_path %>