config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :picks
  resources :teams
  resources :leagues
  resources :drafts
  root to: 'drafts#index'
  get 'players/search'

  resources :picks do
    get :autocomplete_player_name, on: :collection
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/draft.rb
# frozen_string_literal: true

class Draft < ApplicationRecord
  validates :title, presence: true
  after_create_commit { broadcast_prepend_to 'drafts' }
  after_update_commit { broadcast_replace_to 'drafts' }
  after_destroy_commit { broadcast_remove_to 'drafts' }

  belongs_to :league
  validates_presence_of :league, presence: true

  has_many :picks
end

app/controllers/drafts_controller.rb
# frozen_string_literal: true

class DraftsController < ApplicationController
  before_action :set_draft, only: %i[show edit update destroy]

  # GET /drafts
  # GET /drafts.json
  def index
    @drafts = Draft.all
    @draft = Draft.new
  end

  # GET /drafts/1
  # GET /drafts/1.json
  def show
    @draft = Draft.find(params[:id])
    @picks = @draft.picks.order('created_at DESC')
    @pick = Pick.new(draft_id: params[:id])
  end

  # GET /drafts/new
  def new
    @draft = Draft.new
  end

  # GET /drafts/1/edit
  def edit
    @draft = Draft.find(params[:id])
  end

  # POST /drafts
  # POST /drafts.json
  def create
    @draft = Draft.new(draft_params)

    respond_to do |format|
      if @draft.save
        format.html { redirect_to drafts_path, notice: 'Draft was successfully created.' }
        format.json { render :show, status: :created, location: @draft }
      else
        format.html { render :new }
        format.json { render json: @draft.errors, status: :unprocessable_entity }
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@draft, partial: 'drafts/form', locals: { draft: @draft }) }
      end
    end
  end

  # PATCH/PUT /drafts/1
  # PATCH/PUT /drafts/1.json
  def update
    respond_to do |format|
      if @draft.update(draft_params)
        format.html { redirect_to @draft, notice: 'Draft was successfully updated.' }
        format.json { render :show, status: :ok, location: @draft }
      else
        format.html { render :edit }
        format.json { render json: @draft.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drafts/1
  # DELETE /drafts/1.json
  def destroy
    @draft.destroy
    respond_to do |format|
      format.html { redirect_to drafts_url, notice: 'Draft was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_draft
    @draft = Draft.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def draft_params
    params.require(:draft).permit(:title, :league_id)
  end
end

app/helpers/drafts_helper.rb
module DraftsHelper
end

app/views/drafts/_draft.html.erb
<%= turbo_frame_tag dom_id(draft) do %>
  <div class="card">
    <div class="card-body">
      <%= link_to draft.title, draft_path(draft), 'data-turbo-frame': :_top %>
      <br />
      <%= draft.league.name %>
      <div class="btn-group float-right">
        <%= link_to 'Edit', edit_draft_path(draft), class:'btn btn-warning' %>
        &nbsp;
        <%= button_to 'Delete', draft, method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
<% end %>

app/views/drafts/_form.html.erb
<%= form_with(model: draft, id: dom_id(draft)) do |form| %>
  <% if draft.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(draft.errors.count, "error") %> prohibited this draft from being saved:</h2>

      <ul>
        <% draft.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :league %>
    <%= form.collection_select(:league_id, League.all, :id, :name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/drafts/edit.html.erb
<h1>Editing Draft</h1>

<%= turbo_frame_tag dom_id(@draft) do %>
  <div class="card">
    <div class="card-body">
        <%= render 'form', draft: @draft %>
    </div>
  </div>

<% end %>

app/views/drafts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hotwire Drafts</h1>

<%= turbo_stream_from "drafts" %>
<%= turbo_frame_tag  "drafts_form" do %>
  <%= render 'form', draft: @draft %>
<% end %>

<%= turbo_frame_tag "drafts" do %>
  <%= render @drafts %>
<% end %> 

app/views/drafts/new.html.erb
<h1>New Draft</h1>

<%= render 'form', draft: @draft %>

<%= link_to 'Back', drafts_path %>

app/views/drafts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @draft.title %>
</p>

<p>
  <strong>League:</strong>
  <%= @draft.league.name %>
</p>

<%= render 'picks/form', pick: @pick %> 



<%= turbo_stream_from "picks" %>
  <%= turbo_frame_tag "picks" do %>
    <% if @picks %>
      <%= render @picks %>
    <% else %>
    <h3>No picks yet.</h3>
    <% end %>
  <% end %> 



<%= link_to 'Edit', edit_draft_path(@draft) %> |
<%= link_to 'Back', drafts_path %>